[audio]
enable_sounds = true
sound_volume = 1.0

[backdrop]
blur_intensity = 0.67

[bar.default]
background_opacity = 0.67
capsule = true
capsule_padding = 8.0
capsule_thickness = 0.67
center = [ "temp", "cpu", "cat", "workspaces", "ram", "network_rx", "network_tx" ]
contact_shadow = true
end = [
    "tray",
    "notifications",
    "widget_2",
    "widget",
    "nightlight",
    "privacy",
    "bluetooth",
    "volume",
    "input_volume",
    "clock",
    "widget_3",
    "session"
]
font_weight = 700
margin_ends = 0
padding = 8
start = [ "launcher", "active_window", "media" ]
thickness = 40
widget_spacing = 4

[calendar]
enabled = true

[control_center.calendar]
event_time_format = "%H.%M"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "audio"

[[control_center.shortcuts]]
type = "wallpaper"

[desktop_widgets]
enabled = false

[idle]
behavior_order = [ "screen-off", "lock", "lock-and-suspend" ]
pre_action_fade_seconds = 10

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 1800.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 10800.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 900.0

[lockscreen]
fingerprint = false

[lockscreen_widgets]
schema_version = 2
widget_order = [ "lockscreen-login-box" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box"]
    box_height = 196.0
    box_width = 810.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[location]
address = "Bojonegoro, ID"

[nightlight]
enabled = true
temperature_night = 4500

[osd]
background_opacity = 0.74
offset_y = 200
position = "bottom_center"
position_vertical = "bottom_center"

    [osd.kinds]
    media = false

[plugin_settings."goatnath/spotify-lyrics"]
lyrics-panel_open_near_click = true
lyrics-panel_placement = "attached"

[plugins]
enabled = [
    "noctalia/bongocat",
    "dotnetrob/cat",
    "oldirtty/color_picker",
    "pozzoo/hassio",
    "kenn/keybind-cheatsheet",
    "blackbartblues/keymap",
    "weinguyen/procmon",
    "alexander/screen-toolkit"
]

[shell]
external_ip_enabled = true
polkit_agent = true
telemetry_enabled = true
time_format = "{:%H.%M}"

    [shell.launcher]
    app_grid = true

        [shell.launcher.providers.emoji]
        prefix = "e"

    [shell.panel]
    clipboard_placement = "attached"
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    transparency_mode = "soft"
    wallpaper_placement = "floating"

    [shell.screenshot]
    filename_pattern = "Snap %Y-%m-%d %H-%M-%S"
    remember_last_region = true
    show_cursor = true

    [shell.shadow]
    direction = "center"

[theme]
source = "wallpaper"
wallpaper_scheme = "dysfunctional"

    [theme.templates]
    builtin_ids = [ "btop", "foot", "gtk3", "gtk4", "kcolorscheme", "niri", "qt", "wezterm" ]
    community_ids = [ "zen-browser", "telegram", "gimp", "inkscape", "steam", "fastfetch", "obs", "lazygit" ]

[widget.active_window]
icon_size = 16
max_length = 400
min_length = 32

[widget.battery]
enabled = false

[widget.brightness]
enabled = false

[widget.cat]
type = "dotnetrob/cat:cat"

[widget.clipboard]
enabled = false

[widget.clock]
format = "{:%a %d %b %H.%M}"
tooltip_format = "{:%A %d %B %Y %H.%M}"

[widget.control-center]
enabled = false

[widget.cpu]
stat = "cpu_temp"
visualization = "none"

[widget.input_volume]
show_label = false

    [widget.input_volume.actions]
    left = "mic-mute"

[widget.launcher]
glyph = "noctalia"

[widget.media]
art_size = 18
artist_first = true
hide_when_no_media = true
max_length = 320
title_scroll = "always"

[widget.network]
show_vpn_label = true

[widget.network_rx]
network_speed_compact = true
visualization = "none"

[widget.network_tx]
network_speed_compact = true
visualization = "none"

[widget.ram]
visualization = "none"

[widget.sysmon]
stat = "gpu_usage"
visualization = "none"

[widget.temp]
stat = "gpu_temp"
visualization = "none"

[widget.wallpaper]
enabled = false

[widget.widget]
type = "oldirtty/color_picker:widget"

[widget.widget_2]
type = "alexander/screen-toolkit:widget"

[widget.widget_3]
type = "blackbartblues/keymap:widget"

[widget.workspaces]
anchor = true
labels_only_when_occupied = true
