# Docker
alias doc="docker"
alias docrun="docker run"
alias docps="docker ps"
alias docrs="docker restart"
alias docex="docker exec"
alias doclogs="docker logs"
alias docll="doclogs"
alias doclf="doclogs -f"
alias docrm="docker rm"
alias docrmf="docrm -f"
alias docstart="doc start"
alias docstop="doc stop"

# Docker Compose
alias docker-compose="docker compose"
alias dcom="docker-compose"
alias dcomup="docker-compose up"
alias dcomupd="dcomup -d"
alias dcomdo="docker-compose down"
alias dcomrs="dcomup --force-recreate"
alias dcomrsd="dcomrs -d"
alias dcomps="docker-compose ps"
alias dcomex="docker-compose exec"
alias dcomll="docker-compose logs"
alias dcomst="docker-compose stats"
alias dcomlogs="dcomll"
alias dcomlf="dcomll -f"

# System-wide Docker Compose
alias dcf="docker compose -f $HOME/Docker/docker-compose.yaml"
alias dcfup="dcf up"
alias dcfupd="dcfup -d"
alias dcfdo="dcf down"
alias dcfrs="dcfup --force-recreate"
alias dcfrsd="dcfrs -d"
alias dcfps="dcf ps"
alias dcfex="dcf exec"
alias dcfll="dcf logs"
alias dcfst="dcf stats"
alias dcflogs="dcfll"
alias dcflf="dcfll -f"
