# set -as terminal-overrides ",xterm*:Tc"
# set -as terminal-features ",xterm*:RGB"

################
# KEY BINDINGS #
################

# unbind some bindings
unbind "'"
unbind '"'
unbind %
unbind ,
unbind .
unbind [
unbind p

# reload config file
bind r source-file $HOME/.config/tmux/tmux.conf

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set -g prefix C-a
bind -n C-q send-prefix

# split panes using | (or \) and -
bind | split-window -h -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
bind "'" split-window -h -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vim style pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# Pane resize
unbind C-l
bind C-h resize-pane -R
bind C-j resize-pane -U
bind C-k resize-pane -D
bind C-l resize-pane -L
bind Up resize-pane -D
bind Down resize-pane -U
bind Left resize-pane -R
bind Right resize-pane -L

# window switching
bind , previous-window
bind . next-window

# start windows and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# enable mouse mode
set -g mouse on

# remap copy mode, use vi keys
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

# set the scrollback
set -g history-limit 1000000

#######################
# TMUX PLUGIN MANAGER #
#######################

# The Plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "MunifTanjim/tmux-mode-indicator"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-copycat"
set -g @plugin "b0o/tmux-autoreload"
set -g @plugin "janoamaral/tokyo-night-tmux"

# Vim Tmux Navigator
set -g @vim_navigator_mapping_left "C-h"
set -g @vim_navigator_mapping_right "C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"

# Tmux Mode Indicator
set -g @mode_indicator_prefix_mode_style 'bg=blue,fg=white'
set -g @mode_indicator_copy_mode_style 'bg=yellow,fg=white'
set -g @mode_indicator_empty_mode_style 'bg=black,fg=black'
set -g @mode_indicator_sync_mode_style 'bg=red,fg=white'

# Tokyonight
set -g @tokyo-night-tmux_theme "night"
set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_show_git 0
set -g @tokyo-night-tmux_show_hostname 1
set -g @tokyo-night-tmux_window_id_style hide
set -g @tokyo-night-tmux_pane_id_style dsquare
set -g @tokyo-night-tmux_zoom_id_style hsquare

# Initialize TPM
run -b '~/.tmux/plugins/tpm/tpm'

